version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  # build:
  #   docker:
  #     - image: obscurelyme/coffeemaker:latest
  #       auth:
  #         username: obscurelyme
  #         password: $DOCKERHUB_PASSWORD
  #   steps:
  #     - checkout

  #     - run: bash ./scripts/configure.sh
  #     - run: bash ./scripts/build.sh
  #     - run: mkdir release
  #     - run: cp ./build/main ./release/ultra-cosmo-invaders
  #     - run: tar vcfz /tmp/ultra-cosmo-invaders.tar.gz ./release

  #     - store_artifacts:
  #         path: /tmp/ultra-cosmo-invaders.tar.gz

  windows-build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Download Cmake
          command: |
            $ProgressPreference = "$SilentlyContinue"
            Invoke-WebRequest https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-x86_64.zip -OutFile $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip
            Expand-Archive $Env:HOMEPATH\cmake-3.20.6-windows-x86-84.zip -DestinationPath "$Env:ProgramFiles"
            Rename-Item "$Env:ProgramFiles\cmake-3.20.6-windows-x86-64" -NewName CMake
      - checkout
      - run: echo "Hello, World!"
      # - run: ./scripts/configure.bat
      # - run: ./scripts/build.bat
      # - run: mkdir release
      # - run: robocopy build/Debug release /E
      # - run: ./scripts/zip.bat

      - store_artifacts:
          path: ./win-release.zip

workflows:
  version: 2
  coffeemaker_ci:
    jobs:
      - windows-build
