version: 2
jobs:
  build:
    docker:
      - image: obscurelyme/coffeemaker:latest
        auth:
          username: obscurelyme
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: gcc -v
      - run: vcpkg

workflows:
  version: 2
  coffeemaker_ci:
    jobs:
      - build
