#ifndef _game_events_hpp
#define _game_events_hpp

namespace UCI {
  enum Events {
    INIT = 9000,
    PLAYER_LOST_LIFE,
    PLAYER_INCREMENT_SCORE,
    PLAYER_BEGIN_SPAWN,
    PLAYER_COMPLETE_SPAWN,
    PLAYER_POWER_UP_GAINED_IMMUNITY,
    PLAYER_POWER_UP_LOST_IMMUNITY,
    ENEMY_INITIAL_INTERVAL_SPAWN,
    ENEMY_DESTROYED,
    ENEMY_SPAWNED,
    ENEMY_FIRE_MISSILE,
    SHOW_MENU,
    HEADS_UP_DISPLAY_INCREMENT_TIMER
  };
}

#endif
