#ifndef _coffeemaker_spline_hpp
#define _coffeemaker_spline_hpp

#include <string>
#include <vector>

#include "Math.hpp"
#include "Utilities.hpp"
#include "tinysplinecxx.h"

namespace CoffeeMaker {
  /**
   * @brief BSpline class, leverages De Boor's algorithm to compute B-Splines.
   */
  class BSpline {
    public:
    BSpline(size_t numControlPoints = 4);
    ~BSpline();

    std::vector<CoffeeMaker::Math::Point2D> GetControlPoints() const;
    inline size_t NumControlPoints() const { return _tinysplineBSpline->numControlPoints(); }

    void AddControlPoint(const CoffeeMaker::Math::Point2D& point);
    void RemoveControlPointAt(size_t index);

    void SetControlPoints(const std::vector<tinyspline::real>& controlPoints);
    void SetControlPoints(const std::vector<CoffeeMaker::Math::Point2D>& controlPoints);
    void SetControlPoints(const std::vector<CoffeeMaker::Math::Vector2D>& controlPoints);

    void SetControlPointAt(size_t index, CoffeeMaker::Math::Vector2D vector);
    void SetControlPointAt(size_t index, CoffeeMaker::Math::Point2D point);

    /**
     * @brief Generates a vector of Point2Ds that follow the B-Spline curve based on
     * the provided control points.
     *
     * @param precision number of points to generate
     */
    void GenerateCurves(size_t precision = 1000);

    /**
     * @brief Get the entire vector of Point2Ds generated by the given control points.
     *
     * @return std::vector<CoffeeMaker::Math::Point2D>
     */
    std::vector<CoffeeMaker::Math::Point2D> GetPoints() const;

    void Load(const std::string& filename);
    void Save() const;

    /**
     * @brief Returns a Point2D based on a given knot value clamped between 0.0 and 1.0
     * @param knot double value clamped between 0.0 and 1.0
     * @return CoffeeMaker::Math::Point2D
     */
    CoffeeMaker::Math::Point2D Point2DAtKnot(tinyspline::real knot);

    void SetKnotAt(size_t index, tinyspline::real knot);

    std::vector<tinyspline::real> GetKnots() const { return _tinysplineBSpline->knots(); }

    private:
    std::vector<CoffeeMaker::Math::Point2D> _cache;
    Scope<tinyspline::BSpline> _tinysplineBSpline;
    std::vector<CoffeeMaker::Math::Point2D> _curves;
  };

  /**
   * @brief Spline class, combines bezier curves into multiple splines using
   * de Casteljau's algorithm.
   * @deprecated Leverage CoffeeMaker::BSpline instead, which uses De Boor's algorithm.
   */
  class Spline {
    using Vec2 = CoffeeMaker::Math::Vector2D;

    public:
    Spline();
    explicit Spline(float animationTime);
    ~Spline();

    /**
     * @brief Adds a curve to the spline.
     */
    void AddCurve(const Vec2&, const Vec2&, const Vec2&, const Vec2&);
    /**
     * @brief Returns the current calculated weight of the current segment.
     *
     * @return float
     */
    float Weight();
    /**
     * @brief Returns the current position within the spline
     * given the current calculated weight.
     *
     * @return CoffeeMaker::Math::Vector2D
     */
    Vec2 CurrentPosition();

    void Update(float deltaTime);
    void Start();
    void Reset();
    bool IsComplete() const;
    void SetAnimationTime();
    void DebugRender() const;

    private:
    std::vector<Vec2> _spline;
    std::vector<Vec2> _currentSegment;
    float _time;
    unsigned int _offset;
    float _currentTime;
    unsigned int _finalOffset;
    bool _complete;
    float _weight;

    /**
     * @brief Holds a cache of each Vec2 for debugging purposes.
     */
    std::vector<Vec2> _trail;
  };
}  // namespace CoffeeMaker

#endif
