name: coffeemaker-feature-ci
on:
  push:
    paths-ignore:
      - "docs/**"
      - "graphs/**"
      - "scripts/**"
    branches:
      - "feature/**"
      - "bugfix/**"
jobs:

  windows-build:
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Configure
        run: .github/scripts/win/configure.bat
      - name: Build Tests
        run: .github/scripts/win/build-tests.bat
      - name: Run Tests
        run:  ./build/Debug/CoffeeMakerUnitTests.exe
      - name: Build
        run: .github/scripts/win/build.bat

  linux-build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.cache/vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Configure
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install make
          sudo apt-get install yasm
          bash .github/scripts/linux/configure.sh
      - name: Build Tests
        run: bash .github/scripts/linux/build-tests.sh
      - name: Run Tests
        run: |
          chmod +x ./build/CoffeeMakerUnitTests
          ./build/CoffeeMakerUnitTests
      - name: Build
        run: bash .github/scripts/linux/build.sh
