name: coffeemaker-feature-ci
on:
  push:
    paths-ignore:
      - "docs/**"
      - "graphs/**"
      - "scripts/**"
    branches:
      - "feature/**"
      - "bugfix/**"
jobs:
  macos-feature-build:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /Users/runner/.cache/vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Configure
        run: |
          brew install make
          brew install ninja
          brew install autoconf automake libtool yasm
          bash .github/scripts/osx/configure.sh
      - name: Build
        run: bash .github/scripts/osx/build.sh
      - name: Test
        run: |
          chmod +x ./build/CoffeeMakerUnitTests
          ./build/CoffeeMakerUnitTests

  windows-feature-build:
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Configure
        run: .github/scripts/win/configure.bat
      - name: Build
        run: .github/scripts/win/build.bat
      - name: Run Tests
        run: ./build/Debug/CoffeeMakerUnitTests.exe

  linux-feature-build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.cache/vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install make
          sudo apt-get install yasm
          sudo apt install gcc-10 g++-10
      - name: Configure
        run: |
          bash .github/scripts/linux/configure.sh
        env:
          CC: gcc-10
          CXX: g++-10
      - name: Build
        run: bash .github/scripts/linux/build.sh
        env:
          CC: gcc-10
          CXX: g++-10
      - name: Run Tests
        run: |
          chmod +x ./build/CoffeeMakerUnitTests
          ./build/CoffeeMakerUnitTests
