name: CI

on:
  push:
    branches:
      - "**"
    pull_request:
      branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: CppCheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          enable: all
          std: c++20
