name: coffeemaker-release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUTLER_AWS_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.BUTLER_AWS_SECRET_ACCESS_TOKEN }}
          aws-region: us-west-2

      - name: Sync from AWS
        run: |
          aws s3 sync "${{ secrets.S3_BUCKET_NAME }}/$GITHUB_SHA" ./release
