name: coffeemaker-release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: release_setup
        run: |
          echo "::set-output commit=$(git rev-parse HEAD)"

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUTLER_AWS_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.BUTLER_AWS_SECRET_ACCESS_TOKEN }}
          aws-region: us-west-2

      - name: Do a thing
        run: |
          echo Commit was ${{ steps.release_setup.outputs.commit }}
