name: coffeemaker-release
on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUTLER_AWS_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.BUTLER_AWS_SECRET_ACCESS_TOKEN }}
          aws-region: us-west-2

      - name: Sync from AWS
        run: |
          echo $GITHUB_SHA
          aws s3 sync "${{ secrets.S3_BUCKET_NAME }}/ad4001bbb13b3277806addf7126b98afd195650d" ./release
          ls ./release
